CREATE TABLE DATABASE_INSTANCE (
    DATABASE_ID         BIGINT          NOT NULL AUTO_INCREMENT,
    ENVIRONMENT_ID      BIGINT          NOT NULL,
    NAME                VARCHAR(100)    NOT NULL,
    TYPE                BIGINT          NOT NULL,
    HOST                VARCHAR(500)    NOT NULL,
    PORT                VARCHAR(500)    NOT NULL,
    USER                VARCHAR(500)    NOT NULL,
    PASSWORD            VARCHAR(500)    NOT NULL,
    ENCRYPTION_KEY      VARCHAR(1000)   NULL,
    ACTIVE              BIT             NOT NULL DEFAULT 1,
    CREATE_DATE         DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE       DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_DATABASE_INSTANCE PRIMARY KEY (DATABASE_ID),
    CONSTRAINT FK_DATABASE_INSTANCE_ENVIRONMENT FOREIGN KEY (ENVIRONMENT_ID) REFERENCES ENVIRONMENT (ENVIRONMENT_ID)
);