CREATE TABLE USER (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	USERNAME VARCHAR(50) UNIQUE NOT NULL,
	PASSWORD VARCHAR(500) NOT NULL,
	NAME VARCHAR(500) NOT NULL,
	USER_EMAIL VARCHAR(250) NOT NULL,
	ACTIVE BIT NOT NULL DEFAULT 1,
	LOCKED BIT NOT NULL DEFAULT 0,
	EXPIRATION_DATE DATETIME NULL DEFAULT NULL,
	PASSWORD_EXPIRATION_DATE DATETIME NULL DEFAULT NULL,
	CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (ID)
);


CREATE TABLE USER_AUTHENTICATION_TOKEN (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	USER_ID BIGINT NOT NULL,
	TOKEN VARCHAR(500) NOT NULL,
	DEVICE_UUID VARCHAR(250) NOT NULL,
	ACTIVE BIT NOT NULL DEFAULT 0,
	LAST_LOGIN DATETIME NULL,
	LAST_LOGIN_ADDRESS VARCHAR(250) NULL,
	EXPIRATION_DATE DATETIME NULL,
	CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT UAT_PK PRIMARY KEY (ID),
	CONSTRAINT UAT_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);


CREATE TABLE USER_REGISTRATION_KEY (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	KEY_VAL VARCHAR(100) NOT NULL UNIQUE,
	USES_REMAINING INT NOT NULL,
	ACTIVE BIT NOT NULL DEFAULT 1,
	CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (ID)
);

CREATE TABLE USER_REGISTRATION_KEY_USE (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	KEY_ID BIGINT NOT NULL,
	USER_ID BIGINT NOT NULL,
	CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT URKU_PK PRIMARY KEY (ID),
	CONSTRAINT URKU_FK_KEY FOREIGN KEY (KEY_ID) REFERENCES USER_REGISTRATION_KEY(ID),
	CONSTRAINT URKU_FK_USER FOREIGN KEY (USER_ID) REFERENCES USER(ID),
	CONSTRAINT URKU_U_USER_KEY UNIQUE (KEY_ID, USER_ID)
);