CREATE TABLE BUILD_TOKEN (
  BUILD_TOKEN_ID BIGINT       NOT NULL AUTO_INCREMENT,
  NAME           VARCHAR(255) NOT NULL,
  TOKEN_VALUE    VARCHAR(255) NOT NULL,
  ACTIVE         BIT          NOT NULL DEFAULT 1,
  CREATE_DATE    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_DATE  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP
  ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT PK_BUILD_TOKEN PRIMARY KEY (BUILD_TOKEN_ID)
);


