CREATE TABLE APPLICATION (
  APPLICATION_ID   BIGINT       NOT NULL AUTO_INCREMENT,
  APPLICATION_UUID VARCHAR(64)  NOT NULL,
  NAME             VARCHAR(100) NOT NULL,
  ACTIVE           BIT          NOT NULL DEFAULT 1,
  CREATE_DATE      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_DATE    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP
  ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT PK_APPLICATION PRIMARY KEY (APPLICATION_ID),
  CONSTRAINT UK_APPLICATION_UUID UNIQUE (APPLICATION_UUID)
);

CREATE TABLE ENVIRONMENT (
  ENVIRONMENT_ID   BIGINT       NOT NULL AUTO_INCREMENT,
  ENVIRONMENT_UUID VARCHAR(64)  NOT NULL,
  NAME             VARCHAR(100) NOT NULL,
  HOST_NAME        VARCHAR(100) NULL,
  ACTIVE           BIT          NOT NULL DEFAULT 1,
  CREATE_DATE      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_DATE    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP
  ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT PK_ENVIRONMENT PRIMARY KEY (ENVIRONMENT_ID),
  CONSTRAINT UK_ENVIRONMENT_UUID UNIQUE (ENVIRONMENT_UUID)
);

CREATE TABLE APPLICATION_ENVIRONMENT (
  APPLICATION_ENVIRONMENT_ID BIGINT   NOT NULL AUTO_INCREMENT,
  APPLICATION_ID             BIGINT   NOT NULL,
  ENVIRONMENT_ID             BIGINT   NOT NULL,
  ACTIVE                     BIT      NOT NULL DEFAULT 1,
  CREATE_DATE                DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_DATE              DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
  ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT PK_APPLICATION_ENVIRONMENT PRIMARY KEY (APPLICATION_ENVIRONMENT_ID),
  CONSTRAINT FK_APPLICATION_ENVIRONMENT_APPLICATION FOREIGN KEY (APPLICATION_ID) REFERENCES APPLICATION (APPLICATION_ID),
  CONSTRAINT FK_APPLICATION_ENVIRONMENT_ENVIRONMENT FOREIGN KEY (ENVIRONMENT_ID) REFERENCES ENVIRONMENT (ENVIRONMENT_ID)
);

CREATE TABLE APPLICATION_TOKEN (
  APPLICATION_TOKEN_ID BIGINT       NOT NULL AUTO_INCREMENT,
  APPLICATION_ID       BIGINT       NOT NULL,
  NAME                 VARCHAR(255) NOT NULL,
  ACTIVE               BIT          NOT NULL DEFAULT 1,
  CREATE_DATE          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_DATE        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP
  ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT PK_APPLICATION_TOKEN PRIMARY KEY (APPLICATION_TOKEN_ID),
  CONSTRAINT FK_APPLICATION_TOKEN_APPLICATION FOREIGN KEY (APPLICATION_ID) REFERENCES APPLICATION (APPLICATION_ID)
);

CREATE TABLE APPLICATION_ENVIRONMENT_TOKEN (
  APPLICATION_ENVIRONMENT_TOKEN_ID BIGINT       NOT NULL AUTO_INCREMENT,
  APPLICATION_ENVIRONMENT_ID       BIGINT       NOT NULL,
  APPLICATION_TOKEN_ID             BIGINT       NOT NULL,
  TOKEN_VALUE                      VARCHAR(255) NOT NULL,
  ACTIVE                           BIT          NOT NULL DEFAULT 1,
  CREATE_DATE                      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_DATE                    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP
  ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT PK_APPLICATION_ENVIRONMENT_TOKEN PRIMARY KEY (APPLICATION_ENVIRONMENT_TOKEN_ID),
  CONSTRAINT FK_APPLICATION_ENVIRONMENT_TOKEN_APPLICATION_ENVIRONMENT FOREIGN KEY (APPLICATION_ENVIRONMENT_ID) REFERENCES APPLICATION_ENVIRONMENT (APPLICATION_ENVIRONMENT_ID),
  CONSTRAINT FK_APPLICATION_ENVIRONMENT_TOKEN_APPLICATION_TOKEN FOREIGN KEY (APPLICATION_TOKEN_ID) REFERENCES APPLICATION_TOKEN (APPLICATION_TOKEN_ID)
);



